# Generated by Django 5.2.17 on 2026-08-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='allow_calculator',
            field=models.BooleanField(default=False, help_text='Give candidates an on-screen calculator during the test.'),
        ),
    ]
