# Generated by Django 5.2.17 on 2026-08-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_test_allow_calculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='image_caption',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
